export const RESPONSE_ERROR = 'RESPONSE_ERROR';
export const GET_DESTINATIONS_LIST = 'GET_DESTINATIONS_LIST';
export const SET_DESTINATIONS_LIST = 'SET_DESTINATIONS_LIST';
export const GET_NATIONALITIES_LIST = 'GET_NATIONALITIES_LIST';
export const SET_NATIONALITIES_LIST = 'SET_NATIONALITIES_LIST';
export const SET_SEARCH_DATA = 'SET_SEARCH_DATA';
