export {default as SearchPage} from './search.page/search.page';
export {default as SelectDatePage} from './select-date.page/select-data.page';
export {default as SelectDestinationPage} from './select-destination.page/select-destination.page';
export {default as SelectNationalityPage} from './select-nationality.page/select-nationality.page';
export {default as CreateRoomPage} from './create-room.page/create-room.page';
export {default as HotelListPage} from './hotel-list.page/hotel-list.page';
export {default as HotelsFilterPage} from './hotels-filter.page/hotels-filter.page';
export {default as HotelsMapPage} from './hotels-map.page/hotel-map.page';
export {default as TestPage} from './test/test.page';
