// export const API_URL = 'http://hotelian.api';
export const API_URL = 'http://app.hotelian.com';
export const LANGUAGE_URL = 'https://hotelian.com/api/get-translates?lang=';
export const INITIAL_URL = API_URL + '/general/initialize';
export const DESTINATIONS_URL = API_URL + '/hotel/destination-auto-complete';
export const NATIONALITIES_URL = API_URL + '/hotel/nationality-auto-complete';
export const HOTEL_SEARCH_URL = API_URL + '/hotel/search';
export const HOTEL_SEARCH_RESULT_URL = API_URL + '/hotel/get-search-result';
export const USER_TRACK_CODE_URL = API_URL + '/general/get-user-track-code';
export const HOTEL_DETAILS = API_URL + '/hotel/get-hotel-details';
export const HOTEL_ROOMS = API_URL + '/hotel/get-hotel-rooms';
